try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


long_description = '''Utility to let you have a single source of version in your code base.

This utility targets modern Python projects which have layout generated by Poetry, with a pyproject.toml file in place of setup.py. With this layout, the project initially has two places to maintain version string: one in pyproject.toml file and one in some *.py file (normally __init__.py)
'''

setup(
    long_description=long_description,
    name='single-version',
    version='1.2.2',
    description='Small utility to define version string for Poetry-style Python project.',
    python_requires='==3.*,>=3.6.0',
    url="https://github.com/hongquan/single-version",
    project_urls={
        "homepage": "https://github.com/hongquan/single-version",
        "repository": "https://github.com/hongquan/single-version.git"
    },
    author='Nguyễn Hồng Quân',
    author_email='ng.hong.quan@gmail.com',
    license='MIT',
    classifiers=[
        'Intended Audience :: Developers',
        'Topic :: Software Development :: Libraries :: Python Modules',
        'Programming Language :: Python :: 3 :: Only'
    ],
    packages=['single_version'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'first==2.*,>=2.0.0',
        'importlib-metadata==1.*,>=1.6.0; python_version < "3.8"'
    ],
    extras_require={
        "dev": [
            "black==19.*,>=19.10.0.b0", "pytest==5.*,>=5.2.0",
            "pytest-flake8==1.*,>=1.0.0"
        ]
    },
)
